server:
  port: 8082
  max-http-header-size: 10485760
  servlet:
    context-path: /audit
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

